// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// model_hichip
DataFrame model_hichip(NumericVector x, Nullable<NumericVector> y, NumericVector borders, bool yvals);
RcppExport SEXP _sintHiChIP_model_hichip(SEXP xSEXP, SEXP ySEXP, SEXP bordersSEXP, SEXP yvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type borders(bordersSEXP);
    Rcpp::traits::input_parameter< bool >::type yvals(yvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(model_hichip(x, y, borders, yvals));
    return rcpp_result_gen;
END_RCPP
}
// makecombos
DataFrame makecombos(CharacterVector chrom, DataFrame chrpeaks, double mindist, double maxdist);
RcppExport SEXP _sintHiChIP_makecombos(SEXP chromSEXP, SEXP chrpeaksSEXP, SEXP mindistSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type chrpeaks(chrpeaksSEXP);
    Rcpp::traits::input_parameter< double >::type mindist(mindistSEXP);
    Rcpp::traits::input_parameter< double >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(makecombos(chrom, chrpeaks, mindist, maxdist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sintHiChIP_model_hichip", (DL_FUNC) &_sintHiChIP_model_hichip, 4},
    {"_sintHiChIP_makecombos", (DL_FUNC) &_sintHiChIP_makecombos, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sintHiChIP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
