# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

model_hichip <- function(x, y =NA_real_, borders = numeric(), yvals = TRUE) {
    .Call(`_sintHiChIP_model_hichip`, x, y, borders, yvals)
}

makecombos <- function(chrom, chrpeaks, mindist = 0, maxdist = 100000000) {
    .Call(`_sintHiChIP_makecombos`, chrom, chrpeaks, mindist, maxdist)
}

